package com.example.demo.example;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class StockMinuteExample {
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_stock_minute
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_stock_minute
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_minute
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    public StockMinuteExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_minute
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_minute
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_minute
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_minute
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_minute
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_minute
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_minute
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_minute
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_minute
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_minute
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_stock_minute
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtArrivedIsNull() {
            addCriterion("gmt_arrived is null");
            return (Criteria) this;
        }

        public Criteria andGmtArrivedIsNotNull() {
            addCriterion("gmt_arrived is not null");
            return (Criteria) this;
        }

        public Criteria andGmtArrivedEqualTo(Date value) {
            addCriterion("gmt_arrived =", value, "gmtArrived");
            return (Criteria) this;
        }

        public Criteria andGmtArrivedNotEqualTo(Date value) {
            addCriterion("gmt_arrived <>", value, "gmtArrived");
            return (Criteria) this;
        }

        public Criteria andGmtArrivedGreaterThan(Date value) {
            addCriterion("gmt_arrived >", value, "gmtArrived");
            return (Criteria) this;
        }

        public Criteria andGmtArrivedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_arrived >=", value, "gmtArrived");
            return (Criteria) this;
        }

        public Criteria andGmtArrivedLessThan(Date value) {
            addCriterion("gmt_arrived <", value, "gmtArrived");
            return (Criteria) this;
        }

        public Criteria andGmtArrivedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_arrived <=", value, "gmtArrived");
            return (Criteria) this;
        }

        public Criteria andGmtArrivedIn(List<Date> values) {
            addCriterion("gmt_arrived in", values, "gmtArrived");
            return (Criteria) this;
        }

        public Criteria andGmtArrivedNotIn(List<Date> values) {
            addCriterion("gmt_arrived not in", values, "gmtArrived");
            return (Criteria) this;
        }

        public Criteria andGmtArrivedBetween(Date value1, Date value2) {
            addCriterion("gmt_arrived between", value1, value2, "gmtArrived");
            return (Criteria) this;
        }

        public Criteria andGmtArrivedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_arrived not between", value1, value2, "gmtArrived");
            return (Criteria) this;
        }

        public Criteria andSecurityIdIsNull() {
            addCriterion("security_id is null");
            return (Criteria) this;
        }

        public Criteria andSecurityIdIsNotNull() {
            addCriterion("security_id is not null");
            return (Criteria) this;
        }

        public Criteria andSecurityIdEqualTo(String value) {
            addCriterion("security_id =", value, "securityId");
            return (Criteria) this;
        }

        public Criteria andSecurityIdNotEqualTo(String value) {
            addCriterion("security_id <>", value, "securityId");
            return (Criteria) this;
        }

        public Criteria andSecurityIdGreaterThan(String value) {
            addCriterion("security_id >", value, "securityId");
            return (Criteria) this;
        }

        public Criteria andSecurityIdGreaterThanOrEqualTo(String value) {
            addCriterion("security_id >=", value, "securityId");
            return (Criteria) this;
        }

        public Criteria andSecurityIdLessThan(String value) {
            addCriterion("security_id <", value, "securityId");
            return (Criteria) this;
        }

        public Criteria andSecurityIdLessThanOrEqualTo(String value) {
            addCriterion("security_id <=", value, "securityId");
            return (Criteria) this;
        }

        public Criteria andSecurityIdLike(String value) {
            addCriterion("security_id like", value, "securityId");
            return (Criteria) this;
        }

        public Criteria andSecurityIdNotLike(String value) {
            addCriterion("security_id not like", value, "securityId");
            return (Criteria) this;
        }

        public Criteria andSecurityIdIn(List<String> values) {
            addCriterion("security_id in", values, "securityId");
            return (Criteria) this;
        }

        public Criteria andSecurityIdNotIn(List<String> values) {
            addCriterion("security_id not in", values, "securityId");
            return (Criteria) this;
        }

        public Criteria andSecurityIdBetween(String value1, String value2) {
            addCriterion("security_id between", value1, value2, "securityId");
            return (Criteria) this;
        }

        public Criteria andSecurityIdNotBetween(String value1, String value2) {
            addCriterion("security_id not between", value1, value2, "securityId");
            return (Criteria) this;
        }

        public Criteria andDealDateIsNull() {
            addCriterion("deal_date is null");
            return (Criteria) this;
        }

        public Criteria andDealDateIsNotNull() {
            addCriterion("deal_date is not null");
            return (Criteria) this;
        }

        public Criteria andDealDateEqualTo(Integer value) {
            addCriterion("deal_date =", value, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealDateNotEqualTo(Integer value) {
            addCriterion("deal_date <>", value, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealDateGreaterThan(Integer value) {
            addCriterion("deal_date >", value, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealDateGreaterThanOrEqualTo(Integer value) {
            addCriterion("deal_date >=", value, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealDateLessThan(Integer value) {
            addCriterion("deal_date <", value, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealDateLessThanOrEqualTo(Integer value) {
            addCriterion("deal_date <=", value, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealDateIn(List<Integer> values) {
            addCriterion("deal_date in", values, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealDateNotIn(List<Integer> values) {
            addCriterion("deal_date not in", values, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealDateBetween(Integer value1, Integer value2) {
            addCriterion("deal_date between", value1, value2, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealDateNotBetween(Integer value1, Integer value2) {
            addCriterion("deal_date not between", value1, value2, "dealDate");
            return (Criteria) this;
        }

        public Criteria andDealTimeIsNull() {
            addCriterion("deal_time is null");
            return (Criteria) this;
        }

        public Criteria andDealTimeIsNotNull() {
            addCriterion("deal_time is not null");
            return (Criteria) this;
        }

        public Criteria andDealTimeEqualTo(Integer value) {
            addCriterion("deal_time =", value, "dealTime");
            return (Criteria) this;
        }

        public Criteria andDealTimeNotEqualTo(Integer value) {
            addCriterion("deal_time <>", value, "dealTime");
            return (Criteria) this;
        }

        public Criteria andDealTimeGreaterThan(Integer value) {
            addCriterion("deal_time >", value, "dealTime");
            return (Criteria) this;
        }

        public Criteria andDealTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("deal_time >=", value, "dealTime");
            return (Criteria) this;
        }

        public Criteria andDealTimeLessThan(Integer value) {
            addCriterion("deal_time <", value, "dealTime");
            return (Criteria) this;
        }

        public Criteria andDealTimeLessThanOrEqualTo(Integer value) {
            addCriterion("deal_time <=", value, "dealTime");
            return (Criteria) this;
        }

        public Criteria andDealTimeIn(List<Integer> values) {
            addCriterion("deal_time in", values, "dealTime");
            return (Criteria) this;
        }

        public Criteria andDealTimeNotIn(List<Integer> values) {
            addCriterion("deal_time not in", values, "dealTime");
            return (Criteria) this;
        }

        public Criteria andDealTimeBetween(Integer value1, Integer value2) {
            addCriterion("deal_time between", value1, value2, "dealTime");
            return (Criteria) this;
        }

        public Criteria andDealTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("deal_time not between", value1, value2, "dealTime");
            return (Criteria) this;
        }

        public Criteria andOpenPxIsNull() {
            addCriterion("open_px is null");
            return (Criteria) this;
        }

        public Criteria andOpenPxIsNotNull() {
            addCriterion("open_px is not null");
            return (Criteria) this;
        }

        public Criteria andOpenPxEqualTo(BigDecimal value) {
            addCriterion("open_px =", value, "openPx");
            return (Criteria) this;
        }

        public Criteria andOpenPxNotEqualTo(BigDecimal value) {
            addCriterion("open_px <>", value, "openPx");
            return (Criteria) this;
        }

        public Criteria andOpenPxGreaterThan(BigDecimal value) {
            addCriterion("open_px >", value, "openPx");
            return (Criteria) this;
        }

        public Criteria andOpenPxGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("open_px >=", value, "openPx");
            return (Criteria) this;
        }

        public Criteria andOpenPxLessThan(BigDecimal value) {
            addCriterion("open_px <", value, "openPx");
            return (Criteria) this;
        }

        public Criteria andOpenPxLessThanOrEqualTo(BigDecimal value) {
            addCriterion("open_px <=", value, "openPx");
            return (Criteria) this;
        }

        public Criteria andOpenPxIn(List<BigDecimal> values) {
            addCriterion("open_px in", values, "openPx");
            return (Criteria) this;
        }

        public Criteria andOpenPxNotIn(List<BigDecimal> values) {
            addCriterion("open_px not in", values, "openPx");
            return (Criteria) this;
        }

        public Criteria andOpenPxBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("open_px between", value1, value2, "openPx");
            return (Criteria) this;
        }

        public Criteria andOpenPxNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("open_px not between", value1, value2, "openPx");
            return (Criteria) this;
        }

        public Criteria andHighPxIsNull() {
            addCriterion("high_px is null");
            return (Criteria) this;
        }

        public Criteria andHighPxIsNotNull() {
            addCriterion("high_px is not null");
            return (Criteria) this;
        }

        public Criteria andHighPxEqualTo(BigDecimal value) {
            addCriterion("high_px =", value, "highPx");
            return (Criteria) this;
        }

        public Criteria andHighPxNotEqualTo(BigDecimal value) {
            addCriterion("high_px <>", value, "highPx");
            return (Criteria) this;
        }

        public Criteria andHighPxGreaterThan(BigDecimal value) {
            addCriterion("high_px >", value, "highPx");
            return (Criteria) this;
        }

        public Criteria andHighPxGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("high_px >=", value, "highPx");
            return (Criteria) this;
        }

        public Criteria andHighPxLessThan(BigDecimal value) {
            addCriterion("high_px <", value, "highPx");
            return (Criteria) this;
        }

        public Criteria andHighPxLessThanOrEqualTo(BigDecimal value) {
            addCriterion("high_px <=", value, "highPx");
            return (Criteria) this;
        }

        public Criteria andHighPxIn(List<BigDecimal> values) {
            addCriterion("high_px in", values, "highPx");
            return (Criteria) this;
        }

        public Criteria andHighPxNotIn(List<BigDecimal> values) {
            addCriterion("high_px not in", values, "highPx");
            return (Criteria) this;
        }

        public Criteria andHighPxBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("high_px between", value1, value2, "highPx");
            return (Criteria) this;
        }

        public Criteria andHighPxNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("high_px not between", value1, value2, "highPx");
            return (Criteria) this;
        }

        public Criteria andLowPxIsNull() {
            addCriterion("low_px is null");
            return (Criteria) this;
        }

        public Criteria andLowPxIsNotNull() {
            addCriterion("low_px is not null");
            return (Criteria) this;
        }

        public Criteria andLowPxEqualTo(BigDecimal value) {
            addCriterion("low_px =", value, "lowPx");
            return (Criteria) this;
        }

        public Criteria andLowPxNotEqualTo(BigDecimal value) {
            addCriterion("low_px <>", value, "lowPx");
            return (Criteria) this;
        }

        public Criteria andLowPxGreaterThan(BigDecimal value) {
            addCriterion("low_px >", value, "lowPx");
            return (Criteria) this;
        }

        public Criteria andLowPxGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("low_px >=", value, "lowPx");
            return (Criteria) this;
        }

        public Criteria andLowPxLessThan(BigDecimal value) {
            addCriterion("low_px <", value, "lowPx");
            return (Criteria) this;
        }

        public Criteria andLowPxLessThanOrEqualTo(BigDecimal value) {
            addCriterion("low_px <=", value, "lowPx");
            return (Criteria) this;
        }

        public Criteria andLowPxIn(List<BigDecimal> values) {
            addCriterion("low_px in", values, "lowPx");
            return (Criteria) this;
        }

        public Criteria andLowPxNotIn(List<BigDecimal> values) {
            addCriterion("low_px not in", values, "lowPx");
            return (Criteria) this;
        }

        public Criteria andLowPxBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("low_px between", value1, value2, "lowPx");
            return (Criteria) this;
        }

        public Criteria andLowPxNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("low_px not between", value1, value2, "lowPx");
            return (Criteria) this;
        }

        public Criteria andClosePxIsNull() {
            addCriterion("close_px is null");
            return (Criteria) this;
        }

        public Criteria andClosePxIsNotNull() {
            addCriterion("close_px is not null");
            return (Criteria) this;
        }

        public Criteria andClosePxEqualTo(BigDecimal value) {
            addCriterion("close_px =", value, "closePx");
            return (Criteria) this;
        }

        public Criteria andClosePxNotEqualTo(BigDecimal value) {
            addCriterion("close_px <>", value, "closePx");
            return (Criteria) this;
        }

        public Criteria andClosePxGreaterThan(BigDecimal value) {
            addCriterion("close_px >", value, "closePx");
            return (Criteria) this;
        }

        public Criteria andClosePxGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("close_px >=", value, "closePx");
            return (Criteria) this;
        }

        public Criteria andClosePxLessThan(BigDecimal value) {
            addCriterion("close_px <", value, "closePx");
            return (Criteria) this;
        }

        public Criteria andClosePxLessThanOrEqualTo(BigDecimal value) {
            addCriterion("close_px <=", value, "closePx");
            return (Criteria) this;
        }

        public Criteria andClosePxIn(List<BigDecimal> values) {
            addCriterion("close_px in", values, "closePx");
            return (Criteria) this;
        }

        public Criteria andClosePxNotIn(List<BigDecimal> values) {
            addCriterion("close_px not in", values, "closePx");
            return (Criteria) this;
        }

        public Criteria andClosePxBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("close_px between", value1, value2, "closePx");
            return (Criteria) this;
        }

        public Criteria andClosePxNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("close_px not between", value1, value2, "closePx");
            return (Criteria) this;
        }

        public Criteria andTradeVolumeIsNull() {
            addCriterion("trade_volume is null");
            return (Criteria) this;
        }

        public Criteria andTradeVolumeIsNotNull() {
            addCriterion("trade_volume is not null");
            return (Criteria) this;
        }

        public Criteria andTradeVolumeEqualTo(Long value) {
            addCriterion("trade_volume =", value, "tradeVolume");
            return (Criteria) this;
        }

        public Criteria andTradeVolumeNotEqualTo(Long value) {
            addCriterion("trade_volume <>", value, "tradeVolume");
            return (Criteria) this;
        }

        public Criteria andTradeVolumeGreaterThan(Long value) {
            addCriterion("trade_volume >", value, "tradeVolume");
            return (Criteria) this;
        }

        public Criteria andTradeVolumeGreaterThanOrEqualTo(Long value) {
            addCriterion("trade_volume >=", value, "tradeVolume");
            return (Criteria) this;
        }

        public Criteria andTradeVolumeLessThan(Long value) {
            addCriterion("trade_volume <", value, "tradeVolume");
            return (Criteria) this;
        }

        public Criteria andTradeVolumeLessThanOrEqualTo(Long value) {
            addCriterion("trade_volume <=", value, "tradeVolume");
            return (Criteria) this;
        }

        public Criteria andTradeVolumeIn(List<Long> values) {
            addCriterion("trade_volume in", values, "tradeVolume");
            return (Criteria) this;
        }

        public Criteria andTradeVolumeNotIn(List<Long> values) {
            addCriterion("trade_volume not in", values, "tradeVolume");
            return (Criteria) this;
        }

        public Criteria andTradeVolumeBetween(Long value1, Long value2) {
            addCriterion("trade_volume between", value1, value2, "tradeVolume");
            return (Criteria) this;
        }

        public Criteria andTradeVolumeNotBetween(Long value1, Long value2) {
            addCriterion("trade_volume not between", value1, value2, "tradeVolume");
            return (Criteria) this;
        }

        public Criteria andTradeValueIsNull() {
            addCriterion("trade_value is null");
            return (Criteria) this;
        }

        public Criteria andTradeValueIsNotNull() {
            addCriterion("trade_value is not null");
            return (Criteria) this;
        }

        public Criteria andTradeValueEqualTo(BigDecimal value) {
            addCriterion("trade_value =", value, "tradeValue");
            return (Criteria) this;
        }

        public Criteria andTradeValueNotEqualTo(BigDecimal value) {
            addCriterion("trade_value <>", value, "tradeValue");
            return (Criteria) this;
        }

        public Criteria andTradeValueGreaterThan(BigDecimal value) {
            addCriterion("trade_value >", value, "tradeValue");
            return (Criteria) this;
        }

        public Criteria andTradeValueGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("trade_value >=", value, "tradeValue");
            return (Criteria) this;
        }

        public Criteria andTradeValueLessThan(BigDecimal value) {
            addCriterion("trade_value <", value, "tradeValue");
            return (Criteria) this;
        }

        public Criteria andTradeValueLessThanOrEqualTo(BigDecimal value) {
            addCriterion("trade_value <=", value, "tradeValue");
            return (Criteria) this;
        }

        public Criteria andTradeValueIn(List<BigDecimal> values) {
            addCriterion("trade_value in", values, "tradeValue");
            return (Criteria) this;
        }

        public Criteria andTradeValueNotIn(List<BigDecimal> values) {
            addCriterion("trade_value not in", values, "tradeValue");
            return (Criteria) this;
        }

        public Criteria andTradeValueBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("trade_value between", value1, value2, "tradeValue");
            return (Criteria) this;
        }

        public Criteria andTradeValueNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("trade_value not between", value1, value2, "tradeValue");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_stock_minute
     *
     * @mbg.generated do_not_delete_during_merge Wed Jan 13 10:05:15 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_stock_minute
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
