package com.example.demo.bean;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;

public class SecurityInfo {
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_security_info.gmt_create
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_security_info.gmt_modified
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_security_info.security_id
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    private String securityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_security_info.security_type
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    private String securityType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_security_info.display_name
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    private String displayName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_security_info.simple_name
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    private String simpleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_security_info.start_date
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    private String startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_security_info.end_date
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    private String endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_security_info.stock_code
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    private String stockCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_security_info.last_unlimit_day
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    private Integer lastUnlimitDay;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_security_info.id
     *
     * @return the value of t_security_info.id
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_security_info.id
     *
     * @param id the value for t_security_info.id
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_security_info.gmt_create
     *
     * @return the value of t_security_info.gmt_create
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_security_info.gmt_create
     *
     * @param gmtCreate the value for t_security_info.gmt_create
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_security_info.gmt_modified
     *
     * @return the value of t_security_info.gmt_modified
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_security_info.gmt_modified
     *
     * @param gmtModified the value for t_security_info.gmt_modified
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_security_info.security_id
     *
     * @return the value of t_security_info.security_id
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    public String getSecurityId() {
        return securityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_security_info.security_id
     *
     * @param securityId the value for t_security_info.security_id
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    public void setSecurityId(String securityId) {
        this.securityId = securityId == null ? null : securityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_security_info.security_type
     *
     * @return the value of t_security_info.security_type
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    public String getSecurityType() {
        return securityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_security_info.security_type
     *
     * @param securityType the value for t_security_info.security_type
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    public void setSecurityType(String securityType) {
        this.securityType = securityType == null ? null : securityType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_security_info.display_name
     *
     * @return the value of t_security_info.display_name
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_security_info.display_name
     *
     * @param displayName the value for t_security_info.display_name
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName == null ? null : displayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_security_info.simple_name
     *
     * @return the value of t_security_info.simple_name
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    public String getSimpleName() {
        return simpleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_security_info.simple_name
     *
     * @param simpleName the value for t_security_info.simple_name
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    public void setSimpleName(String simpleName) {
        this.simpleName = simpleName == null ? null : simpleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_security_info.start_date
     *
     * @return the value of t_security_info.start_date
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_security_info.start_date
     *
     * @param startDate the value for t_security_info.start_date
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    public void setStartDate(String startDate) {
        this.startDate = startDate == null ? null : startDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_security_info.end_date
     *
     * @return the value of t_security_info.end_date
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_security_info.end_date
     *
     * @param endDate the value for t_security_info.end_date
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_security_info.stock_code
     *
     * @return the value of t_security_info.stock_code
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    public String getStockCode() {
        return stockCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_security_info.stock_code
     *
     * @param stockCode the value for t_security_info.stock_code
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    public void setStockCode(String stockCode) {
        this.stockCode = stockCode == null ? null : stockCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_security_info.last_unlimit_day
     *
     * @return the value of t_security_info.last_unlimit_day
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    public Integer getLastUnlimitDay() {
        return lastUnlimitDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_security_info.last_unlimit_day
     *
     * @param lastUnlimitDay the value for t_security_info.last_unlimit_day
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    public void setLastUnlimitDay(Integer lastUnlimitDay) {
        this.lastUnlimitDay = lastUnlimitDay;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table t_security_info
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    public enum Column {
        id("id", "id", "BIGINT", false),
        gmtCreate("gmt_create", "gmtCreate", "TIMESTAMP", false),
        gmtModified("gmt_modified", "gmtModified", "TIMESTAMP", false),
        securityId("security_id", "securityId", "VARCHAR", false),
        securityType("security_type", "securityType", "VARCHAR", false),
        displayName("display_name", "displayName", "VARCHAR", false),
        simpleName("simple_name", "simpleName", "VARCHAR", false),
        startDate("start_date", "startDate", "VARCHAR", false),
        endDate("end_date", "endDate", "VARCHAR", false),
        stockCode("stock_code", "stockCode", "VARCHAR", false),
        lastUnlimitDay("last_unlimit_day", "lastUnlimitDay", "INTEGER", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_security_info
         *
         * @mbg.generated Tue Mar 02 16:09:33 CST 2021
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_security_info
         *
         * @mbg.generated Tue Mar 02 16:09:33 CST 2021
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_security_info
         *
         * @mbg.generated Tue Mar 02 16:09:33 CST 2021
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_security_info
         *
         * @mbg.generated Tue Mar 02 16:09:33 CST 2021
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_security_info
         *
         * @mbg.generated Tue Mar 02 16:09:33 CST 2021
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_security_info
         *
         * @mbg.generated Tue Mar 02 16:09:33 CST 2021
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_security_info
         *
         * @mbg.generated Tue Mar 02 16:09:33 CST 2021
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_security_info
         *
         * @mbg.generated Tue Mar 02 16:09:33 CST 2021
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_security_info
         *
         * @mbg.generated Tue Mar 02 16:09:33 CST 2021
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_security_info
         *
         * @mbg.generated Tue Mar 02 16:09:33 CST 2021
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_security_info
         *
         * @mbg.generated Tue Mar 02 16:09:33 CST 2021
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_security_info
         *
         * @mbg.generated Tue Mar 02 16:09:33 CST 2021
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_security_info
         *
         * @mbg.generated Tue Mar 02 16:09:33 CST 2021
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_security_info
         *
         * @mbg.generated Tue Mar 02 16:09:33 CST 2021
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_security_info
         *
         * @mbg.generated Tue Mar 02 16:09:33 CST 2021
         */
        public static Column[] all() {
            return Column.values();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_security_info
         *
         * @mbg.generated Tue Mar 02 16:09:33 CST 2021
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_security_info
         *
         * @mbg.generated Tue Mar 02 16:09:33 CST 2021
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}
