package com.example.demo.bean;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;

public class StockMinute {
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_minute.gmt_create
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_minute.gmt_modified
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_minute.gmt_arrived
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    private Date gmtArrived;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_minute.security_id
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    private String securityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_minute.deal_date
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    private Integer dealDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_minute.deal_time
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    private Integer dealTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_minute.open_px
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    private BigDecimal openPx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_minute.high_px
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    private BigDecimal highPx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_minute.low_px
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    private BigDecimal lowPx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_minute.close_px
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    private BigDecimal closePx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_minute.trade_volume
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    private Long tradeVolume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_stock_minute.trade_value
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    private BigDecimal tradeValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_minute.id
     *
     * @return the value of t_stock_minute.id
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_minute.id
     *
     * @param id the value for t_stock_minute.id
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_minute.gmt_create
     *
     * @return the value of t_stock_minute.gmt_create
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_minute.gmt_create
     *
     * @param gmtCreate the value for t_stock_minute.gmt_create
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_minute.gmt_modified
     *
     * @return the value of t_stock_minute.gmt_modified
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_minute.gmt_modified
     *
     * @param gmtModified the value for t_stock_minute.gmt_modified
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_minute.gmt_arrived
     *
     * @return the value of t_stock_minute.gmt_arrived
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    public Date getGmtArrived() {
        return gmtArrived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_minute.gmt_arrived
     *
     * @param gmtArrived the value for t_stock_minute.gmt_arrived
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    public void setGmtArrived(Date gmtArrived) {
        this.gmtArrived = gmtArrived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_minute.security_id
     *
     * @return the value of t_stock_minute.security_id
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    public String getSecurityId() {
        return securityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_minute.security_id
     *
     * @param securityId the value for t_stock_minute.security_id
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    public void setSecurityId(String securityId) {
        this.securityId = securityId == null ? null : securityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_minute.deal_date
     *
     * @return the value of t_stock_minute.deal_date
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    public Integer getDealDate() {
        return dealDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_minute.deal_date
     *
     * @param dealDate the value for t_stock_minute.deal_date
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    public void setDealDate(Integer dealDate) {
        this.dealDate = dealDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_minute.deal_time
     *
     * @return the value of t_stock_minute.deal_time
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    public Integer getDealTime() {
        return dealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_minute.deal_time
     *
     * @param dealTime the value for t_stock_minute.deal_time
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    public void setDealTime(Integer dealTime) {
        this.dealTime = dealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_minute.open_px
     *
     * @return the value of t_stock_minute.open_px
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    public BigDecimal getOpenPx() {
        return openPx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_minute.open_px
     *
     * @param openPx the value for t_stock_minute.open_px
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    public void setOpenPx(BigDecimal openPx) {
        this.openPx = openPx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_minute.high_px
     *
     * @return the value of t_stock_minute.high_px
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    public BigDecimal getHighPx() {
        return highPx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_minute.high_px
     *
     * @param highPx the value for t_stock_minute.high_px
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    public void setHighPx(BigDecimal highPx) {
        this.highPx = highPx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_minute.low_px
     *
     * @return the value of t_stock_minute.low_px
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    public BigDecimal getLowPx() {
        return lowPx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_minute.low_px
     *
     * @param lowPx the value for t_stock_minute.low_px
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    public void setLowPx(BigDecimal lowPx) {
        this.lowPx = lowPx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_minute.close_px
     *
     * @return the value of t_stock_minute.close_px
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    public BigDecimal getClosePx() {
        return closePx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_minute.close_px
     *
     * @param closePx the value for t_stock_minute.close_px
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    public void setClosePx(BigDecimal closePx) {
        this.closePx = closePx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_minute.trade_volume
     *
     * @return the value of t_stock_minute.trade_volume
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    public Long getTradeVolume() {
        return tradeVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_minute.trade_volume
     *
     * @param tradeVolume the value for t_stock_minute.trade_volume
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    public void setTradeVolume(Long tradeVolume) {
        this.tradeVolume = tradeVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_stock_minute.trade_value
     *
     * @return the value of t_stock_minute.trade_value
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    public BigDecimal getTradeValue() {
        return tradeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_stock_minute.trade_value
     *
     * @param tradeValue the value for t_stock_minute.trade_value
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    public void setTradeValue(BigDecimal tradeValue) {
        this.tradeValue = tradeValue;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table t_stock_minute
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    public enum Column {
        id("id", "id", "BIGINT", false),
        gmtCreate("gmt_create", "gmtCreate", "TIMESTAMP", false),
        gmtModified("gmt_modified", "gmtModified", "TIMESTAMP", false),
        gmtArrived("gmt_arrived", "gmtArrived", "TIMESTAMP", false),
        securityId("security_id", "securityId", "VARCHAR", false),
        dealDate("deal_date", "dealDate", "INTEGER", false),
        dealTime("deal_time", "dealTime", "INTEGER", false),
        openPx("open_px", "openPx", "DECIMAL", false),
        highPx("high_px", "highPx", "DECIMAL", false),
        lowPx("low_px", "lowPx", "DECIMAL", false),
        closePx("close_px", "closePx", "DECIMAL", false),
        tradeVolume("trade_volume", "tradeVolume", "BIGINT", false),
        tradeValue("trade_value", "tradeValue", "DECIMAL", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_stock_minute
         *
         * @mbg.generated Wed Jan 13 10:05:15 CST 2021
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_stock_minute
         *
         * @mbg.generated Wed Jan 13 10:05:15 CST 2021
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_stock_minute
         *
         * @mbg.generated Wed Jan 13 10:05:15 CST 2021
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_stock_minute
         *
         * @mbg.generated Wed Jan 13 10:05:15 CST 2021
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_stock_minute
         *
         * @mbg.generated Wed Jan 13 10:05:15 CST 2021
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_stock_minute
         *
         * @mbg.generated Wed Jan 13 10:05:15 CST 2021
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_stock_minute
         *
         * @mbg.generated Wed Jan 13 10:05:15 CST 2021
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_stock_minute
         *
         * @mbg.generated Wed Jan 13 10:05:15 CST 2021
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_stock_minute
         *
         * @mbg.generated Wed Jan 13 10:05:15 CST 2021
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_stock_minute
         *
         * @mbg.generated Wed Jan 13 10:05:15 CST 2021
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_stock_minute
         *
         * @mbg.generated Wed Jan 13 10:05:15 CST 2021
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_stock_minute
         *
         * @mbg.generated Wed Jan 13 10:05:15 CST 2021
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_stock_minute
         *
         * @mbg.generated Wed Jan 13 10:05:15 CST 2021
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_stock_minute
         *
         * @mbg.generated Wed Jan 13 10:05:15 CST 2021
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_stock_minute
         *
         * @mbg.generated Wed Jan 13 10:05:15 CST 2021
         */
        public static Column[] all() {
            return Column.values();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_stock_minute
         *
         * @mbg.generated Wed Jan 13 10:05:15 CST 2021
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_stock_minute
         *
         * @mbg.generated Wed Jan 13 10:05:15 CST 2021
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}
