package com.example.demo.mapper;

import com.example.demo.bean.SecurityInfo;
import com.example.demo.example.SecurityInfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SecurityInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_security_info
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    long countByExample(SecurityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_security_info
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    int deleteByExample(SecurityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_security_info
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_security_info
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    int insert(SecurityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_security_info
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    int insertSelective(SecurityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_security_info
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    List<SecurityInfo> selectByExample(SecurityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_security_info
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    SecurityInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_security_info
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    int updateByExampleSelective(@Param("record") SecurityInfo record, @Param("example") SecurityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_security_info
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    int updateByExample(@Param("record") SecurityInfo record, @Param("example") SecurityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_security_info
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    int updateByPrimaryKeySelective(SecurityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_security_info
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    int updateByPrimaryKey(SecurityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_security_info
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    int batchInsert(@Param("list") List<SecurityInfo> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_security_info
     *
     * @mbg.generated Tue Mar 02 16:09:33 CST 2021
     */
    int batchInsertSelective(@Param("list") List<SecurityInfo> list, @Param("selective") SecurityInfo.Column ... selective);
}
