package com.example.demo.mapper;

import com.example.demo.bean.StockMinute;
import com.example.demo.example.StockMinuteExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface StockMinuteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_minute
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    long countByExample(StockMinuteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_minute
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    int deleteByExample(StockMinuteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_minute
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_minute
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    int insert(StockMinute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_minute
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    int insertSelective(StockMinute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_minute
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    List<StockMinute> selectByExample(StockMinuteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_minute
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    StockMinute selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_minute
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    int updateByExampleSelective(@Param("record") StockMinute record, @Param("example") StockMinuteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_minute
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    int updateByExample(@Param("record") StockMinute record, @Param("example") StockMinuteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_minute
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    int updateByPrimaryKeySelective(StockMinute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_minute
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    int updateByPrimaryKey(StockMinute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_minute
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    int batchInsert(@Param("list") List<StockMinute> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_stock_minute
     *
     * @mbg.generated Wed Jan 13 10:05:15 CST 2021
     */
    int batchInsertSelective(@Param("list") List<StockMinute> list, @Param("selective") StockMinute.Column ... selective);
}
