package com.example.demo.mapper;

import com.example.demo.bean.TradeDay;
import com.example.demo.example.TradeDayExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TradeDayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade_day
     *
     * @mbg.generated Thu Jan 14 19:27:48 CST 2021
     */
    long countByExample(TradeDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade_day
     *
     * @mbg.generated Thu Jan 14 19:27:48 CST 2021
     */
    int deleteByExample(TradeDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade_day
     *
     * @mbg.generated Thu Jan 14 19:27:48 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade_day
     *
     * @mbg.generated Thu Jan 14 19:27:48 CST 2021
     */
    int insert(TradeDay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade_day
     *
     * @mbg.generated Thu Jan 14 19:27:48 CST 2021
     */
    int insertSelective(TradeDay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade_day
     *
     * @mbg.generated Thu Jan 14 19:27:48 CST 2021
     */
    List<TradeDay> selectByExample(TradeDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade_day
     *
     * @mbg.generated Thu Jan 14 19:27:48 CST 2021
     */
    TradeDay selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade_day
     *
     * @mbg.generated Thu Jan 14 19:27:48 CST 2021
     */
    int updateByExampleSelective(@Param("record") TradeDay record, @Param("example") TradeDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade_day
     *
     * @mbg.generated Thu Jan 14 19:27:48 CST 2021
     */
    int updateByExample(@Param("record") TradeDay record, @Param("example") TradeDayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade_day
     *
     * @mbg.generated Thu Jan 14 19:27:48 CST 2021
     */
    int updateByPrimaryKeySelective(TradeDay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade_day
     *
     * @mbg.generated Thu Jan 14 19:27:48 CST 2021
     */
    int updateByPrimaryKey(TradeDay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade_day
     *
     * @mbg.generated Thu Jan 14 19:27:48 CST 2021
     */
    int batchInsert(@Param("list") List<TradeDay> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade_day
     *
     * @mbg.generated Thu Jan 14 19:27:48 CST 2021
     */
    int batchInsertSelective(@Param("list") List<TradeDay> list, @Param("selective") TradeDay.Column ... selective);}
